<table width="100%" style="
  background:black;
  border-bottom:4px solid #00ffff;
  box-shadow:0 0 15px #00ffff;
">
  <tr>
    <td width="33%"></td>

    <td width="33%" align="center">
      <img src="reactron_logo2.jpg" width="250" height="108">
    </td>

    <td width="33%" align="right" style="padding-right:20px;">
      <a href="index.htm">
        <img src="botn_menu2.jpg" width="75" height="70">
      </a>
    </td>
  </tr>
</table>
