t <table style="position: fixed; bottom: 5px; left: 10px; font-size: 14px;">
t <tr>
t <td>
c h 1 <input type="text" readonly id="current_time" style="background-color: transparent; border: 0px; width: 80px;" value="%s">
t </td>
t <td>
c h 2 <input type="text" readonly id="current_date" style="background-color: transparent; border: 0px; width: 120px;" value="%s">
t </td>
t </tr>
t </table>
